version: '3.8'

services:
  elasticsearch:
    build: .
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    container_name: clearticket-es
    environment:
      - discovery.type=single-node # 단일 노드(로컬 개발용)
      - xpack.security.enabled=false # 로컬 개발 편의를 위한 보안 기능 off
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # 메모리 제한(최소 1GB)
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data  # 컨테이너가 꺼져도 데이터가 보존되도록 볼륨 연결
  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.2
    container_name: clearticket-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # 키바나가 바라볼 엘라스틱서치 주소
    ports:
      - "5601:5601" # 웹 브라우저 접속용 키바나 포트
    depends_on:
      - elasticsearch # 엘라스틱서치가 먼저 켜진 후 키바나 실행

volumes:
  es_data:
    driver: local
