server:
  port: 8080

spring:
  application:
    name: ClearTicket
  config:
    import: optional:file:./config.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/clearticket
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
#      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

app:
  dummy-user:
    id: hong123
    password: "Test1234!"
    name: 홍길동
    email: test@test.com