server:
  port: 8080

spring:
  application:
    name: ClearTicket
  config:
    import: optional:file:./config.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${mail.username}"
    password: "${mail.password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: jdbc:postgresql://localhost:5432/clearticket
    username: postgres
    password: clearticket
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  elasticsearch:
    uris: http://localhost:9200
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
lemonsqueezy:
  api-key: "${LEMON_SQUEEZY_API_KEY}"
  store-id: "410829"
  variant-id: "1806370"
LEMON_SQUEEZY_API_KEY: ""
app:
  dummy-user:
    id: hong123
    password: "Test1234!"
    name: 홍길동
    email: test@test.com